# Generated by Django 6.0.4 on 2026-05-31 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_marca_rubro_rename_precio_producto_precio_costo_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marca',
            table='marca',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
        migrations.AlterModelTable(
            name='rubro',
            table='rubro',
        ),
    ]
