# Generated by Django 3.2.25 on 2026-05-13 19:38

from django.db import migrations, models




class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),

    ]


